src/MyBlog.Web/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyBlog.Core.Contracts;
using MyBlog.Web.Models;

namespace MyBlog.Web.Controllers
{
    public class TagsController : Controller
    {
        private readonly ITagService tagService;
        private readonly IPostService postService;

        public TagsController(ITagService tagService, IPostService postService)
        {
            this.tagService = tagService;
            this.postService = postService;
        }

        [HttpGet]
        public ActionResult Cloud()
        {
            var tags = tagService.Cloud().Select(tm => new { name = tm.Name, url = Url.RouteUrl("PostsByTag", new { name = tm.Name }), postCount = tm.PostCount }).ToArray();
            return Json(new { tags }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult PostsFor(string tag)
        {
            var posts = (string.IsNullOrEmpty(tag) ? postService.List(): postService.ByTag(tag)).ToList();

            return View(new PostsByTagViewModel()
                {
                    Tag = tag,
                    Posts = AutoMapper.Mapper.Map<ICollection<PostModel>>(posts) 
                });
        }
    }
}

src/MyBlog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>
        <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css"/>
        <link href="@Url.Content("~/Content/bootstrap-responsive.css")" rel="stylesheet" type="text/css"/>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/highlightStyles/vs.css")" rel="stylesheet" type="text/css">

        <script src="@Url.Content("~/Scripts/jquery-1.9.1.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/knockout-2.2.1.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/knockout.mapping-latest.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/highlight.pack.js")"></script>
    </head>
    
    <script type="text/javascript">
        $(document).ready(function () {
            if (!String.prototype.format) {
                String.prototype.format = function () {
                    var args = arguments;
                    return this.replace(/{(\d+)}/g, function (match, number) {
                        return typeof args[number] != 'undefined' ? args[number] : match;
                    });
                };
            }
            if (!String.prototype.toTitleCase) {
                String.prototype.toTitleCase = function () {
                    var str = this;
                    return str.replace(/\w\S*/g, function (txt) { return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase(); });
                };
            }

            !function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + "://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs");

            var viewModel = function (cloudUrl) {
                var self = this;
                self.tags = ko.observableArray();

                self.fetch = function () {
                    $.get(cloudUrl, {}, function (response) {
                        self.tags(response.tags);
                    });
                };
            };

            var vm = new viewModel('@Url.Action("Cloud", "Tags")');
            vm.fetch();
            ko.applyBindings(vm, document.getElementById('tagCloud'));
            hljs.initHighlightingOnLoad();
        });
    </script>

    <body>
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="http://idontknowthedomainyet.org">Blog about life and programming</a>
                    <ul class="nav"> 
                        <li><a href="http://blog.ploeh.dk/archive.html">Archive</a></li>	
                        <li><a href="http://blog.ploeh.dk/pages.html">Pages</a></li>
                        <li><a href="http://blog.ploeh.dk/tags.html">Tags</a></li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="container">
            <div class="content">
                <div class="page-header">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="row">
                    <div class="span10">
                        @RenderBody()
                        <pre>
                            <code>
                                public interface IRepository
                                {
                                    void Start();
                                }
                                
                                public class Repository: IRepository 
                                {
                                    public void Start() 
                                    {
                                        int x = 20/5;
                                        String value = DateTime.UtcNow.ToString();
                                    }
                                }
                            </code>
                        </pre>
                    </div>
                    <div class="span3 pull-right">
                        My name is Gleb and I'm a web developer
                        <div id="tagCloud" class="tag_box">
                            Topics I blog about:
                            <!-- ko foreach: tags -->
                            <a data-bind="attr: { href: url }">
                                <text data-bind="text: name"></text> 
                                <span data-bind="text: postCount"></span>
                            </a>
                            <!-- /ko -->
                        </div>
                        
                        <div class="twitter-feed">
                            <a class="twitter-timeline" href="https://twitter.com/chester89" data-theme="light" data-tweet-limit="5" data-widget-id="421260939233476609">Tweets by me</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>